APT {
    FTPArchive {
        Release {
            Origin "Procursus(roothide-alt)";
            Label "Procursus(roothide-alt)";
            Architectures iphoneos-arm64e;
            Suite stable;
            Version 1.0a1;
            Components "main";
            Description "Distribution of essential tools for iPhoneOS (ALT)";
        };
    };
};
